### ISSUE TITLE
Could not load Cockpit

### ISSUE THREAD

**Issue by marigianna** [datakurre/camunda-cockpit-plugin-jupyter#1]
Hello Asko @datakurre,

Happy New Year! 

I tried out the plugin but could not load the cockpit in any case (tried both 7.14, 7.15 in Chrome incognito windows). I have also deleted my history and browsing data). Do you have any tips?

Best regards,
Marigianna

**Comment by datakurre** [comment]
@marigianna Did you try by just following the README or by integrating to your own Camunda? If so, what kind of distrobution?

I assume that you did not even see the ”Jupyter Lab” tab on the cockpit top menu?

**Comment by marigianna** [comment]
Hi @datakurre 

I followed the readme and tried both 7.14 and 7.15. No cockpit was not loading at all. 
P.S. you can find me on camundaconferences.slack.com namespace for more direct communication

Best regards,
Marigianna

**Comment by datakurre** [comment]
Thanks! I’ll be in touch, once I have retries the instructions myself.

**Comment by datakurre** [comment]
I am sorry but, I was unable to reproduce the issue by literally following the README example for 7.15. (That said, 7.14 probably won't work, because of minor differences in Camunda frontend plugin API.) The example for 7.15 should also work for 7.16.

Most obvious issue to debug is, if http://localhost:8080/camunda/app/cockpit/scripts/config.js?bust=123456 returns the version from the plugin (with 'scripts/jupyter-lite-route.js' in it).

Most most critical part of the example cmd is -v $(pwd)/camunda-cockpit-plugin-jupyter:/camunda/webapps/camunda/app/cockpit/scripts/:ro camunda/camunda-bpm-platform:7.15.0 which should override scripts folder in the Docker container with the plugin repository. $(pwd)/camunda-cockpit-plugin-jupyter  is probably Linux Bash specific and could be replaced with full path to the cloned repository.

**Comment by marigianna** [comment]
Hello,
It is working!
I installed npm and did install and build, then i changed to project root folder and followed your instructions for 7.15 but with WSL terminal instead of powershell.

These links helped:
https://camunda.com/blog/2020/08/all-new-frontend-plugin-system-for-cockpit-starting-with-camunda-bpm-7-14/
https://github.com/camunda/camunda-bpm-examples/tree/master/cockpit/cockpit-greetings-plugin
Thanks for your support 💯 👍
